### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gowtham758550** [Ph0enixKM/browser-zen-mode#1]
Make the css configurable so we can hide whatever we want and also need to hide the shorts menu in the sidebar.

**Comment by Ph0enixKM** [comment]
Thanks for feedback, I’ll give this plugin more attention and extend it more.

**Comment by Ph0enixKM** [comment]
@gowtham758550 The configurable CSS as well as the bug regarding the videos tab have been fixed/added. The new version of **Zen Mode 2.0.0** should be available at **Chrome Web Store** and **Mozilla Addons** shortly

**Comment by Ph0enixKM** [comment]
Please stay tuned for version 2.0.1 as I spotted couple of issues with chaos mode. Sorry for inconvenience. The new version should be released in 7 days at max. The reason for that is that the validation process of addons in chrome web store usually takes a long time to validate. The Firefox version 2.0.1 will probably be available to download later today.

**Comment by gowtham758550** [comment]
Hey, Sorry for the late reply. Video tab issue is resolved and configurable CSS is nice. 
Really great work.

FYI - I am using your extension in firefox

**Comment by Ph0enixKM** [comment]
I'm glad I could help
