### ISSUE TITLE
{BUG} Issue with the gif [after turning on Zen Mode]

### ISSUE THREAD

**Issue by Weemizo** [Ph0enixKM/browser-zen-mode#4]
The bug happens after returning from the main page to subscription page. If it's a feature then - when scrolling down through subscriptions - the image doesn't follow [remains in the same spot]
![image](https://user-images.githubusercontent.com/60063669/211216746-3f8e14a0-8e1a-4b1b-9498-98c826d028a5.png)
![image](https://user-images.githubusercontent.com/60063669/211216824-8e155223-bdfe-4610-a205-0b99fc7a89e5.png)
![image](https://user-images.githubusercontent.com/60063669/211216833-a6a432be-7240-4083-8008-afc5b1d4a441.png)

**Comment by Weemizo** [comment]
Not to mention - after refreshing the subscription page the logo seems to disappear.
![image](https://user-images.githubusercontent.com/60063669/211217039-4dace438-3a4d-420e-98a9-bb64edba7d5c.png)

**Comment by Ph0enixKM** [comment]
@Weemizo Thanks, I’ll take a closer look on that.

**Comment by Ph0enixKM** [comment]
@Weemizo The default behavior of this extension should be to enable you to see the content for Subscribers as it is up to you what you want to watch. Thus the new version 2.1.1 will allow you to see the content. The main purpose will be to block any unwantend content that is shoveled up the users' throat by YouTube.

Stay tuned for the updates - will be available for download later today
